In [1]:
%load_ext autoreload
%autoreload 2

# Proporciona funciones para interactuar con el sistema operativo (como rutas de archivos).
import os  

# Permite modificar aspectos del entorno de ejecución de Python, como la lista de rutas de búsqueda de módulos (sys.path).
import sys 

# Sube un nivel desde /Ejercicio 2/
root_dir = os.path.abspath('..')  
sys.path.append(root_dir)

import pandas as pd

# Importa las funciones personalizadas desde utils.
import utils.functions_Python_BBDD as f

In [2]:
query = "SELECT TOP 10* FROM cm.resumen_flota"
df_buques = f.ejecutar_consulta_sql(query, database_key="SGP_CUADROSMANDO")

# Mostrar las primeras filas del DataFrame resultante
df_buques.head()

,IdBuque,CFR,Año Construccion,Edad,Motivo Alta Censo,Fecha Alta Censo,Eslora Total,Eslora PP,Arqueo GT,Material del Casco,...,idpuertobase,Puerto Base,Provincia Puerto Base,Censo por Modalidad,IdCenso,IdTipoEstado,IdCCAAPuertoBase,CALADERO,SUBCALADERO,esfuerzo
0,26241,ESP000000279,1970,54,Alta en Censo,1989-05-10 00:00:00.0000,28.15,26.01,238.00,Acero,...,5664,Burela,LUGO,"ARTES FIJAS EN ZONAS CIEM VB, VI,VII y VIIIabde.",33,1,11,2.CALADERO COMUNITARIO,"ZONAS CIEM VB, VI,VII y VIIIabde",279
1,26281,ESP000000334,1960,64,Alta en Censo,1989-05-10 00:00:00.0000,8.55,NaN,3.05,Madera,...,5664,Burela,LUGO,ARTES MENORES EN CANTABRICO NW,6,1,11,1.CALADERO NACIONAL,CANTABRICO NW,137
2,26293,ESP000000348,1978,43,Alta en Censo,1989-05-10 00:00:00.0000,28.00,NaN,112.00,Acero,...,6271,Tarragona,TARRAGONA,ARRASTRE DE FONDO EN EL MEDITERRANEO,14,1,9,1.CALADERO NACIONAL,MEDITERRANEO,166
3,26311,ESP000000371,1978,40,Alta en Censo,1989-05-10 00:00:00.0000,28.00,NaN,96.97,Acero,...,6271,Tarragona,TARRAGONA,ARRASTRE DE FONDO EN EL MEDITERRANEO,14,1,9,1.CALADERO NACIONAL,MEDITERRANEO,166
4,26317,ESP000000377,1969,55,Alta en Censo,1989-05-10 00:00:00.0000,17.78,14.25,22.89,Acero,...,6334,Vilanova y la Geltrú,BARCELONA,CERCO EN EL MEDITERRANEO,12,1,9,1.CALADERO NACIONAL,MEDITERRANEO,203